{
 "title": "prod-kafka-dashboard",
 "description": "Kafka resource usage and throughput",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "jmx-job",
    "query": "label_values(kafka_server_KafkaServer_Value,job)"
   },
   {
    "name": "broker_id",
    "label": "Broker",
    "query": "label_values(kafka_server_KafkaServer_Value, instance)"
   },
   {
    "name": "topic",
    "label": "Topic",
    "query": "label_values(kafka_log_Log_Value,topic)"
   },
   {
    "name": "groupId",
    "label": "消费组",
    "query": "label_values(kafka_consumer_group_ConsumerLagMetrics_Value, groupId)"
   }
  ]
 },
 "panels": [
  {
   "title": "每个topic的生产请求速率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_server_BrokerTopicMetrics_Count{job=\"$job\",  instance=~\"$broker_id\",topic=~\"$topic\",name=\"TotalProduceRequestsPerSec\"}[5m])) by (topic)",
     "legendFormat": "{{topoic}}"
    }
   ]
  },
  {
   "title": "每个topic的消费请求速度",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_server_BrokerTopicMetrics_Count{job=\"$job\",  instance=~\"$broker_id\",topic=~\"$topic\",name=\"TotalFetchRequestsPerSec\"}[5m])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  { "title": "集群健康检查", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "激活状态控制器数量",
   "type": "stat",
   "description": "Number of active controllers in the cluster.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_KafkaController_Value{job=\"$job\",instance=~\"$broker_id\", name=\"ActiveControllerCount\"})"
    }
   ]
  },
  {
   "title": "在线broker数量",
   "type": "stat",
   "description": "Number of Brokers Online",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(kafka_server_ReplicaManager_Count{job=\"$job\",instance=~\"$broker_id\"})"
    }
   ]
  },
  {
   "title": "Unclean Leader选举比率",
   "type": "stat",
   "description": "Unclean leader election rate",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_ControllerStats_OneMinuteRate{job=\"$job\",instance=~\"$broker_id\", name=\"UncleanLeaderElectionsPerSec\"})"
    }
   ]
  },
  {
   "title": "未平衡到首选副本的数量",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_KafkaController_Value{job=\"$job\",instance=~\"$broker_id\",name=\"PreferredReplicaImbalanceCount\"})"
    }
   ]
  },
  {
   "title": "Broker网络吞吐量",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_server_BrokerTopicMetrics_Count{job=\"$job\",instance=~\"$broker_id\",topic!=\"\",name=\"BytesInPerSec\"}[5m]))",
     "legendFormat": "Bytes in"
    },
    {
     "expr": "sum(rate(kafka_server_BrokerTopicMetrics_Count{job=\"$job\",instance=~\"$broker_id\",topic!=\"\",name=\"BytesOutPerSec\"}[5m]))",
     "legendFormat": "Bytes out"
    }
   ]
  },
  {
   "title": "在线分区数",
   "type": "stat",
   "description": "Partitions that are online",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_ReplicaManager_Value{job=\"$job\",instance=~\"$broker_id\",name=\"PartitionCount\"})"
    }
   ]
  },
  {
   "title": "离线分区数量",
   "type": "stat",
   "description": "Number of partitions that dont have an active leader and are hence not writable or readable.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_KafkaController_Value{job=\"$job\",instance=~\"$broker_id\",name=\"OfflinePartitionsCount\"})"
    }
   ]
  },
  {
   "title": "没有保持同步的分区数",
   "type": "stat",
   "description": "Number of under-replicated partitions (| ISR | < | all replicas |).",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_ReplicaManager_Value{job=\"$job\",instance=~\"$broker_id\",name=\"UnderReplicatedPartitions\"})"
    }
   ]
  },
  {
   "title": "isr小于最少同步副本的分区数",
   "type": "stat",
   "description": "Number of partitions under min insync replicas.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kafka_cluster_Partition_Value{job=\"$job\",instance=~\"$broker_id\",name=\"UnderMinIsr\"})"
    }
   ]
  },
  { "title": "消息的吞吐量", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "每个Broker的消息速率",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "iops", "label": "Messages/s" }
   ],
   "targets": [
    {
     "expr": "sum without(topic)(rate(kafka_server_BrokerTopicMetrics_Count{job=~\"$job\",instance=~\"$broker_id\",topic=~\"$topic\",name=\"MessagesInPerSec\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "每个Broker每秒入站字节数",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum without(topic)(rate(kafka_server_BrokerTopicMetrics_Count{job=\"$job\",instance=~\"$broker_id\",topic=~\"$topic\",name=\"BytesInPerSec\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "每个Broker上每秒出站字节数",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum without(topic)(rate(kafka_server_BrokerTopicMetrics_Count{job=\"$job\",instance=~\"$broker_id\",topic=~\"$topic\",name=\"BytesOutPerSec\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "每个topic消息速率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "iops", "label": "Messages/s" }
   ],
   "targets": [
    {
     "expr": "sum without(instance)(rate(kafka_server_BrokerTopicMetrics_Count{job=\"$job\",instance=~\"$broker_id\",topic=~\"$topic\",name=\"MessagesInPerSec\"}[5m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "每个topic入站流量速率",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum without(instance)(rate(kafka_server_BrokerTopicMetrics_Count{job=\"$job\",instance=~\"$broker_id\",topic=~\"$topic\",name=\"BytesInPerSec\"}[5m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "每个topic的出站流量速率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum without(instance)(rate(kafka_server_BrokerTopicMetrics_Count{job=\"$job\",instance=~\"$broker_id\",topic=~\"$topic\",name=\"BytesOutPerSec\"}[5m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  { "title": "消息积压", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "消息积压",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max(kafka_consumer_group_ConsumerLagMetrics_Value{job=\"$job\", groupId=~\"$groupId\", topic=~\"$topic\"}) by (groupId, topic)",
     "legendFormat": "{{groupId}}(topic: {{topic}})"
    }
   ]
  }
 ]
}